export const projects = [
  {
    id: 1,
    title: "Social Media App",
    description: "A social networking app with features like sharing posts, comments, likes, and following/unfollowing user profiles.",
    image: "/social medea app.jpg",
    technologies: ["Node.js", "PostgreSQL", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/social-media-app",
    demoUrl: "https://social-media-j5ch.onrender.com/",
    color: "#FF6B6B",
  },
  {
    id: 2,
    title: "Authentication System",
    description: "A full-featured authentication system using Passport.js with multiple authentication strategies, including OAuth2 for Google, GitHub, and Facebook, as well as session-based authentication with email and password.",
    image: "/authentification.jpg",
    technologies: ["Node.js", "Express", "Passport.js", "MongoDB", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/passport-authentication-app",
    demoUrl: "",
    color: "#4ECDC4",
  },
  {
    id: 3,
    title: "Weather Forecasting App",
    description: "A weather application that displays the current weather for a given city and provides a 5-day forecast. Includes a button to get the weather for the user's current location.",
    image: "/weather.jpg",
    technologies: ["React", "Material-UI", "OpenWeather API", "OpenCageData API"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/react-weather-app",
    demoUrl: "https://weathergeo.netlify.app/",
    color: "#45B8AC",
  },
  {
    id: 4,
    title: "Social Media App with Laravel",
    description: "A social networking app built with Laravel and Inertia.js, featuring post sharing, comments, likes, and user profile management.",
    image: "/social medea laravel.jpg",
    technologies: ["Laravel", "Inertia", "MySQL", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/social-media-app-with-laravel",
    demoUrl: null,
    color: "#9370DB",
  },
  {
    id: 5,
    title: "Stock Management System",
    description: "A stock management system built with PHP and Bootstrap, allowing administrators to manage products, users, and invoices efficiently.",
    image: "/stock management.webp",
    technologies: ["PHP", "Bootstrap", "MySQL", "JavaScript"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/stock-managment",
    demoUrl: null,
    color: "#F4A460",
  },

];
