export const projects = [
  {
    id: 1,
    title: "ShareFiring Landing Page & Dashboard",
    description: "A freelance project delivering a modern landing page and an interactive dashboard for managing content and users. Built with React, Tailwind CSS, Inertia.js, Laravel, and MySQL.",
    image: "/sharefirng landing page.png",
    technologies: ["React", "Tailwind CSS", "Inertia.js", "Laravel", "MySQL"],
    githubUrl: null,
    demoUrl: "https://sharefiring.com/",
    color: "#1E90FF",
  },
  {
    id: 2,
    title: "Social Media App",
    description: "A full-stack social networking app with post sharing, comments, likes, and following/unfollowing user profiles.",
    image: "/social medea app.jpg",
    technologies: ["Node.js", "PostgreSQL", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/social-media-app",
    demoUrl: "https://social-media-j5ch.onrender.com/",
    color: "#FF6B6B",
  },
  {
    id: 3,
    title: "Authentication System",
    description: "An authentication system using Passport.js with OAuth2 (Google, GitHub, Facebook), session-based, and local strategies.",
    image: "/authentification.jpg",
    technologies: ["Node.js", "Express", "Passport.js", "MongoDB", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/passport-authentication-app",
    demoUrl: "",
    color: "#4ECDC4",
  },
  {
    id: 4,
    title: "Weather Forecasting App",
    description: "A weather app with city search, location detection, and 5-day forecasts, using OpenWeather API and OpenCageData API.",
    image: "/weather.jpg",
    technologies: ["React", "Material-UI", "OpenWeather API", "OpenCageData API"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/react-weather-app",
    demoUrl: "https://weathergeo.netlify.app/",
    color: "#45B8AC",
  },
  {
    id: 5,
    title: "Social Media App with Laravel",
    description: "A social networking app built with Laravel and Inertia.js, including post sharing, comments, likes, and profile management.",
    image: "/social medea laravel.jpg",
    technologies: ["Laravel", "Inertia", "MySQL", "React", "Material-UI"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/social-media-app-with-laravel",
    demoUrl: null,
    color: "#9370DB",
  },
  {
    id: 6,
    title: "Stock Management System",
    description: "A PHP-based system for managing products, users, and invoices, with a Bootstrap interface and MySQL backend.",
    image: "/stock management.webp",
    technologies: ["PHP", "Bootstrap", "MySQL", "JavaScript"],
    githubUrl: "https://github.com/Mohamed-Messaoudene/stock-managment",
    demoUrl: null,
    color: "#F4A460",
  },
];
